### ISSUE TITLE
Rendering cannot be drawn! Type: KPolylineImpl ID: undefined

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/vscode-lingua-franca#126]
![image](https://github.com/lf-lang/vscode-lingua-franca/assets/33707478/49f246e5-f8c5-4bc6-8aeb-7ec54fc274ed)

Seen in VS Code after opening [Python/src/ModalActions.lf](https://github.com/lf-lang/lingua-franca/blob/master/test/Python/src/modal_models/ModalActions.lf).

**Comment by soerendomroes** [comment]
I cannot reproduce this with the released LF extension since TraceTesting, which is required for ModalActions, has errors. 

![image](https://github.com/lf-lang/vscode-lingua-franca/assets/6419799/926ef9bd-6f5a-43f9-9c84-9034d7d32d07)

**Comment by lhstrh** [comment]
This error relates to what is in `main`. We want to fix this before doing a new release...

**Comment by petervdonovan** [comment]
I am confused... There is nothing to fix because `main` is correct, right? The problem is merely that we haven't released the updated LF extension yet.

**Comment by lhstrh** [comment]
Now I'm confused. How was this observation made? In the latest release, or in `main`? I assumed the latter because the former has been out for months.

**Comment by soerendomroes** [comment]
It would be nice to include this type of information in the issue together with steps to reproduce.

Does the error still occur after a reload or is it a general problem of the model?

**Comment by petervdonovan** [comment]
> It would be nice to include this type of information in the issue together with steps to reproduce.

Yes, I'll try to remember that next time.

> Does the error still occur after a reload or is it a general problem of the model?

Just now I re-opened Python/src/ModalActions.lf and the diagram opened correctly (I failed to reproduce the bug that I reported).

**Comment by lhstrh** [comment]
Sorry for the noise, @soerendomroes :smile:
