### ISSUE TITLE
Comments in empty reactors are removed when saving 

### ISSUE THREAD

**Issue by ChadliaJerad** [lf-lang/vscode-lingua-franca#133]
In VSCode, when you declare a reactor, add comments (before anything else), and save, the comments are removed.

This is counterproductive, as sometimes one needs to organize thoughts first (defining the architecture), and saving is a reflex.

**Comment by ChadliaJerad** [comment]
I am not using a release or pre-release. The reason is that I don't want the editor to complain about what is different in the branch I am working on.

**Comment by lhstrh** [comment]
What are you using then? Can't debug if we don't know what version of the code you're using...

**Comment by ChadliaJerad** [comment]
I am installing from: https://github.com/lf-lang/vscode-lingua-franca (main branch)

**Comment by lhstrh** [comment]
OK, that's the same branch that the nightly pre-release uses (albeit with a more up-to-date `lingua-franca`).
