### ISSUE TITLE
"Reindent Lines" replaces spaces with tabs

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#15]
In VS Code, the "Reindent Lines" command changes spaces to tabs. Is there a way we can setup our extension to always use spaces?

**Comment by petervdonovan** [comment]
I suspect that this is unrelated to our extension and more related to other user and workspace settings, as well as possibly the whitespace that already appears in the file.

I was able to reproduce this by entering this into `.vscode/settings.json`:
```
{
    "editor.detectIndentation": false,
    "editor.insertSpaces": false
}
```

However, if I do not have those settings, then "Reindent Lines" uses four spaces, not tabs.

Feel free to re-open if I am likely to be mistaken.

**Comment by edwardalee** [comment]
Wait, why do we want to replace spaces with tabs?  We should use spaces, not tabs.  Tabs render differently for different people, making code hard to read.

**Comment by petervdonovan** [comment]
Yes. The point of my closing the issue is that I believe the Lingua Franca VS Code extension is not responsible for managing the editor's use of tabs -- it is not because I think it is acceptable to use tabs. I don't think anyone here would advocate for the use of tabs.
