### ISSUE TITLE
Out of Java heap space while compiling LDS

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/vscode-lingua-franca#152]
I'm not sure how to reproduce this since it seems to depend on the state of the Gradle daemon(s) (IntelliJ, which also uses Gradle, was running at the time). **After killing them and trying again, it worked,** so this issue is not currently blocking progress.

```
> starting Gradle build...
Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space

> Task :core:compileJava FAILED
An exception has occurred in the compiler (17.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.OutOfMemoryError: Java heap space
```

The following change in `build_lds.ts` did NOT solve the issue:
```sh
export _JAVA_OPTIONS="-Xms512m -Xmx4096m" && ./gradlew lsp:assemble
```

I also tried it with a max of 8 GB (`-Xmx8192m`) instead of 4, but that did not work either.

**Comment by lhstrh** [comment]
Is this still an issue, or can this be closed?

**Comment by petervdonovan** [comment]
I haven't seen this issue in a long time, and it might have just been a quirk of my personal dev setup at the time rather than being an issue for users. Let's close it.
