### ISSUE TITLE
"Go to definition" when double clicking on element in diagram does not work

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#16]
In Epoch, a very useful feature of the diagrams is that when you click on a graphical element, the corresponding LF code gets highlighted. In VS Code, this doesn't yet work. It would be great if we could introduce this feature. Tagging @a-sr for visibility.

**Comment by a-sr** [comment]
This feature should be already available. Unfortunately, in the current release the defaults are not configured in the way one would expect. The selection synchronization from text to diagram is active but diagram to text is inactive by default. In the next release, it will be the other way around.
As a workaround, you can go to Settings -> Extensions -> KLighD Diagram and deactivate "Initial Should Select Diagram" and activate "Initial Should Select Text" instead.

**Comment by lhstrh** [comment]
Ah, thanks for clarifying! Adding a link to the [release page of klighd-vscode](https://github.com/kieler/klighd-vscode/releases) and keeping this issue open as a reminder to document this in the `README.md`.

**Comment by lhstrh** [comment]
Added note in README (see https://github.com/lf-lang/vscode-lingua-franca/commit/b57ef3b264b443751256331904abc57f578a07e4).
