### ISSUE TITLE
Generated files and directories do not appear in Windows

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/vscode-lingua-franca#19]
LFC works fine on Windows, but for some reason (likely inadequate privileges?) the compiler does not generate directories when invoked from VS Code.

This results in errors like
```
java.io.IOException: Cannot run program "npm" (in directory "c:\c%3A\vscode-lingua-franca\lingua-franca\test\TypeScript\src-gen\After"): CreateProcess error=2, The system cannot find the file specified
```

**Comment by Soroosh129** [comment]
There is also `c:\c%3A` here, which is `c:\c:\`.

**Comment by lhstrh** [comment]
Was this error thrown when compiling an LF file with TypeScript target (since it's attempting to run `npm`)?

**Comment by petervdonovan** [comment]
@Soroosh129 was right on both issues -- thank you Soroush!

Yes, the error was thrown when compiling with the TypeScript target. It is still true that calls to `npm` via `ProcessBuilder` do not seem to work on Windows, but that seems to be a separate problem that also exists for `lfc`. I am closing this issue and #20.
