### ISSUE TITLE
Remove use of `Buffer()`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#2]
(node:9936) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by petervdonovan** [comment]
The string `new Buffer(` appears in multiple transitive dependencies, including `buffer-crc32`, `tunnel`, `qs`, `typescript`, `yazl`, `azure-devops-node-api`, `typed-rest-client`, `deep-extend`, and `fd-slicer`.

From a quick glance at `package-lock.json`, it appears that many (maybe all?) of these are dependencies come from `vsce`. Bumping the version number of `vsce` did not get rid of the deprecation warning, even after deleting `package-lock.json`, and I would not have expected it to, either. The most recent `vsce` version still depends on `fd-slicer`, for example, and no new versions have come out for that dependency for a few years.

Perhaps we will have to close this as a wontfix?

**Comment by lhstrh** [comment]
Thanks for investigating this! Won't fix sounds fair to me :-)
