### ISSUE TITLE
Files target property does not work within VS Code extension

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/vscode-lingua-franca#41]
To replicate, open, for example, experimental-lingua-franca/Python/src/Pac-Man/PacMan.lf and invoke the compiler using Ctrl + Shift + P, then Lingua Franca:Build.  You then have to hunt for the output, but I eventually found this:

![image](https://user-images.githubusercontent.com/8513334/162806038-f5259a20-d5b3-41eb-adb5-c7a86863c9d3.png)

This file compiles fine using `lfc` or Epoch.

**Comment by lhstrh** [comment]
I think this has to do with the very recent update of the files target property to allow referencing entire directories. The current version of the extension does not yet have that update. The new release will.

**Comment by lhstrh** [comment]
Closing this because it is not an issue on `releases/v1.0.1`
