### ISSUE TITLE
Create a nightly release

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#56]
For users who want to be on the bleeding edge, we publish a nightly built artifact, but we don't tag a particular ref corresponding to that artifact. We should fix this in the same manner this is done in [epoch](https://github.com/lf-lang/epoch).

**Comment by lhstrh** [comment]
This is a great suggestion. Let's do that.

**Comment by lhstrh** [comment]
This is important, but in order to have this, we first need to make sure that our CI works reliably. I.e., we need to fix #108 first.

**Comment by cmnrd** [comment]
Should we consider this addressed by the pre-release version on the marketplace? I don't think providing the vsix file on GitHub would add a lot of benefit.

**Comment by lhstrh** [comment]
What we do in this repo is slightly different from what happens in https://github.com/lf-lang/epoch, which I think is a slightly better setup. The different is that a `latest` branch is kept in, of which the `HEAD` is tagged `nightly`. While the nightly release VS Code extension does exactly the same thing (it pulls the latest from https://github.com/lf-lang/lingua-franca and builds the extension based on that), there is no way to trace the extension back to any particular ref. I do think that we should fix this, so let me repurpose this issue for that.
