### ISSUE TITLE
Using the "Build and Run" command on a file with TypeScript target doesn't run the program

### ISSUE THREAD

**Issue by billy-bao** [lf-lang/vscode-lingua-franca#64]
I am on Mac OS Monterey 12.4, using Bash.
When choosing the "Build and Run" command using the VS Code extension on a TypeScript target, the program doesn't run, but rather starts the node interactive environment. This is the output:
```
cd /Users/billybao/lf/test
bash --login -c node src-gen/HelloWorld/dist/HelloWorld.js

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) BillydeMacBook-Pro:test billybao$ cd /Users/billybao/lf/test
(base) BillydeMacBook-Pro:test billybao$ bash --login -c node src-gen/HelloWorld/dist/HelloWorld.js
Welcome to Node.js v18.4.0.
Type ".help" for more information.
> 
```

Suggested fix:
`bash --login -c node src-gen/HelloWorld/dist/HelloWorld.js` -> 
`bash --login -c "node src-gen/HelloWorld/dist/HelloWorld.js"`

**Comment by petervdonovan** [comment]
Closed by [#1265](https://github.com/lf-lang/lingua-franca/pull/1265).
