### ISSUE TITLE
Can't get rid of options menu for diagrams

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/vscode-lingua-franca#79]
On a Mac at least, in VS Code, when I open the Options menu for the diagrams, as shown below, there is no way to get rid of it. It just sits there obscuring the diagram.
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/8513334/183382916-d399f21f-8d96-4996-8ff0-bdb852133800.png">

**Comment by lhstrh** [comment]
If you click on the active tab (in your screenshot, the icon with the faders), then the options window should disappear...

**Comment by lhstrh** [comment]
@lsk567 or @Soroosh129: could you confirm that this works normally on Mac? If so, let's mark this `invalid` and close...

**Comment by lsk567** [comment]
@edwardalee Does the sidebar collapse if you click this button?
<img width="1452" alt="183382916-d399f21f-8d96-4996-8ff0-bdb852133800" src="https://user-images.githubusercontent.com/7968955/184180865-3f39b7e7-42a0-416e-982f-d5cedb3a7a03.png">

**Comment by edwardalee** [comment]
Ah, the sidebar collapses if you click the button *twice*. But not if you click it once. Pretty cryptic.
