### ISSUE TITLE
"Webview is disposed" error

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#81]
Sometimes, when opening the diagram, the following error is shown (and the diagram is not rendered):

![image](https://user-images.githubusercontent.com/19938940/188811480-bd9821db-9d75-4b0f-a488-9f30f8523c0a.png)

The error goes away after restarting VS Code.

**Comment by soerendomroes** [comment]
Do you have any error message in addition to "Webview is disposed?
How to you reproduce the issue? Reload VS Code until it happens, just close and open the diagram, or are you refreshing the diagram?
What model did you use?

**Comment by lhstrh** [comment]
I've been experiencing the problem with various models, and it happens after having used the extension for some amount of time; in which case opening the diagram of a newly opened file immediately results in the error. Next time it happens I'll try to collect more information...

**Comment by lhstrh** [comment]
Related (or subsumed) by #113.

**Comment by lhstrh** [comment]
Haven't seen this error in quite a while. Close?

**Comment by petervdonovan** [comment]
OK. Even if this issue still exists, it probably does not belong in this repo because it seems more related to KlighD.
