### ISSUE TITLE
`Build and Run` reports "Build failed" while `Build` does not

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/vscode-lingua-franca#99]
Compilation succeeds; no errors (only a warning). Running `Build` points the user to the produced binary. Running `Build and Run` errors out with "Build failed". This was observed in `v0.4.1` on Linux.

**Comment by petervdonovan** [comment]
Probably this is because the generator result includes the location of the binary, but is missing the build command for some reason. It might help to know which file this happens on, or at least which target language.

**Comment by lhstrh** [comment]
:+1: This is happening in C. I'll point you to the files in question.

**Comment by Jakio815** [comment]
This is also happening for me on Windows WSL. It also happens on Python targets. The build doesn't actually fails, but it says errors, and so the Build and Run does not run.
